# Generated by Django 3.2.5 on 2021-09-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_auto_20210907_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
